server:
  port: 8080

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true

  datasource:
    platform: h2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect